### ISSUE TITLE
USB enumeration

### ISSUE THREAD

**Issue by keyboard-magpie** [TeXitoi/keyseebee#8]
Me again, so sorry.

Both halves of my 0.1 build now present bootloader, following the LDO fix.

However when flashed with keyberon from this repo neither enumerate/appear in lsusb. 
Running dmesg on linux shows enumeration error 71.

I tried flashing a known working qmk f072 bin, which does enumerate fine and presents a usb keyboard.

Any thoughts? Having looked through the commits to keyberon I couldn't see anything that changed clock speed tree etc that might affect this.

Many thanks

**Comment by TeXitoi** [comment]
https://github.com/TeXitoi/keyberon/pull/36

So 2 workarounds:
 * switch to rust 1.47
 * update to keyberon master

The first solution is the simplest.

**Comment by keyboard-magpie** [comment]
Swapped to rust 1.47 and all good!

**Comment by gwenzek** [comment]
I also had the same issue
upgrading to https://github.com/TeXitoi/keyseebee/tree/keyberon-master (8654780
)
works well with `rustc 1.49.0 (e1884a8e3 2020-12-29)`

**Comment by camrbuss** [comment]
I too suffered from the generic_array panic on the master branch with rustc 1.48.0

Just checking out the `keyberon-master` branch as gwenzek said solved the panic by grabbing keyberon master branch. Can something get merged into the keyseebee master branch so that new comers (like me) don't build a panicking firmware?

**Comment by TeXitoi** [comment]
Yeah, i have to release keyberon v0.2

**Comment by TeXitoi** [comment]
Keyseebee firmware now use the master keyberon.
